# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
# check these on https://fabricmc.net/versions.html
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.15.11

# Fabric API
fabric_version=0.102.1+1.21.1

# Mod Properties
mod_version = 1.2.12
mod_id=hollowwoods
maven_group = xyz.costamiri
archives_base_name = hollowwoods-fabric
